/**
 * Regenerate fixtures/13f/*.expected.json from the committed fixtures.
 * Run via: npm run fixtures:expected
 *
 * Offline — reads only files on disk.
 *
 * The point of expected.json is to be verifiable *independently of the
 * parser*, otherwise it just records whatever the parser happened to produce.
 * Every filing's cover page carries the filer's own declared totals
 * (summaryPage/tableEntryTotal and tableValueTotal), so each generated file
 * records whether the parsed rows agree with what the filer itself declared,
 * and the run fails loudly if they do not.
 *
 * Note tableValueTotal is stated in the filing's own units ($ thousands for
 * pre-2023 periods), so it is compared before unit normalization.
 */
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { parse13f } from "../lib/edgar/parse13f";

const FIXTURE_DIR = join("fixtures", "13f");
const WHOLE_DOLLAR_FROM = "2023-01-01";

interface ManifestEntry {
  label: string;
  cik: string;
  accession: string;
  formType: string;
  filedAt: string;
  periodOfReport: string;
  coverPage: string;
  informationTable: string;
  note: string;
}

interface SpotCheck {
  rowIndex: number;
  nameOfIssuer: string;
  cusip: string;
  shareClass: string | null;
  putCall: "Put" | "Call" | null;
  shares: number | null;
  principalAmt: number | null;
  valueUsd: number;
}

/** Five rows spread across the table, deterministic for a given fixture. */
function pickSpotChecks(count: number): number[] {
  if (count === 0) return [];
  const wanted = Math.min(5, count);
  const picked = new Set<number>();
  for (let i = 0; i < wanted; i++) {
    picked.add(Math.round((i * (count - 1)) / Math.max(wanted - 1, 1)));
  }
  return [...picked].sort((a, b) => a - b);
}

function main(): void {
  const manifest = JSON.parse(
    readFileSync(join(FIXTURE_DIR, "manifest.json"), "utf-8"),
  ) as ManifestEntry[];

  let failures = 0;

  for (const entry of manifest) {
    const cover = readFileSync(join(FIXTURE_DIR, entry.coverPage), "utf-8");
    const info = readFileSync(join(FIXTURE_DIR, entry.informationTable), "utf-8");

    const parsed = parse13f(cover, info, {
      accessionNo: entry.accession,
      filedAt: entry.filedAt,
    });

    const multiplier = parsed.filing.periodOfReport < WHOLE_DOLLAR_FROM ? 1000 : 1;
    const totalValueUsd = parsed.holdings.reduce((s, h) => s + h.valueUsd, 0);

    // Compare against the filer's own declaration, in the filing's own units.
    const declared = parsed.declared;
    const parsedTotalInFilingUnits = totalValueUsd / multiplier;
    const countAgrees =
      declared.entryTotal === null ||
      declared.entryTotal === parsed.holdings.length;
    const totalAgrees =
      declared.valueTotal === null ||
      Math.abs(declared.valueTotal - parsedTotalInFilingUnits) < 1;

    if (!countAgrees || !totalAgrees) {
      failures++;
      console.error(
        `  ✗ ${entry.label}: parsed rows=${parsed.holdings.length} total=${parsedTotalInFilingUnits} ` +
          `but filer declared entries=${declared.entryTotal} total=${declared.valueTotal}`,
      );
      continue;
    }

    const spotChecks: SpotCheck[] = pickSpotChecks(parsed.holdings.length).map(
      (i) => {
        const h = parsed.holdings[i];
        return {
          rowIndex: h.rowIndex,
          nameOfIssuer: h.nameOfIssuer,
          cusip: h.cusip,
          shareClass: h.shareClass,
          putCall: h.putCall,
          shares: h.shares,
          principalAmt: h.principalAmt,
          valueUsd: h.valueUsd,
        };
      },
    );

    const expected = {
      _note:
        "Generated by npm run fixtures:expected. rowCount and totalValueUsd are " +
        "cross-checked against the filer's own declared totals on the cover page.",
      accession: entry.accession,
      cik: parsed.filer.cik,
      filerName: parsed.filer.name,
      filerSlug: parsed.filer.slug,
      formType: parsed.filing.formType,
      periodOfReport: parsed.filing.periodOfReport,
      filedAt: parsed.filing.filedAt,
      isAmendment: parsed.filing.isAmendment,
      amendmentType: parsed.filing.amendmentType,

      rowCount: parsed.holdings.length,
      /** Whole USD. For pre-2023 periods this is the filing's figure x1000. */
      totalValueUsd,

      /** Straight from the cover page, in the filing's own units. */
      declaredByFiler: {
        entryTotal: declared.entryTotal,
        valueTotal: declared.valueTotal,
        valueUnits: multiplier === 1000 ? "thousands of USD" : "USD",
      },

      distinctCusips: new Set(parsed.holdings.map((h) => h.cusip)).size,
      spotChecks,
      warnings: parsed.warnings,
    };

    const path = join(FIXTURE_DIR, `${entry.label}.expected.json`);
    writeFileSync(path, JSON.stringify(expected, null, 2) + "\n", "utf-8");
    console.log(
      `  ✓ ${entry.label}: ${parsed.holdings.length} rows, ` +
        `$${totalValueUsd.toLocaleString("en-US")} (agrees with filer)`,
    );
  }

  if (failures > 0) {
    console.error(`\n${failures} fixture(s) disagree with the filer's totals.`);
    process.exit(1);
  }
  console.log("\n✅ expected.json regenerated; all agree with filer totals.");
}

main();
